#!/bin/bash
set -ex

mkdir -p test/wiremock_scope
cd test/wiremock_scope

wiremock_jar='wiremock-1.54-standalone.jar'
if [ ! -f "$wiremock_jar" ]; then
  curl "http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/1.54/${wiremock_jar}" > "${wiremock_jar}"
fi

java -jar wiremock-1.54-standalone.jar  --port 9999 --proxy-all="http://localhost:5001" --record-mappings --verbose
